version: 0.2

phases:

  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo "Installing dependencies..."
      - pip install -r requirements.txt -t lib

  build:
    commands:
      - echo "Zipping deployment package..."
      - cd lib
      - zip -r9 ../deployment_package.zip .
      - cd ..
      - zip -g deployment_package.zip lambda_function.py

  post_build:
    commands:
      - echo "Uploading deployment package to S3..."
      - aws s3 cp deployment_package.zip s3://s3-doordash-landing/

      - echo "Updating Lambda function via S3..."
      - aws lambda update-function-code --function-name doordash_transform --s3-bucket s3-doordash-landing --s3-key deployment_package.zip
      - echo "Deployment complete!"

      - echo "Creating Lambda layer from python-dotenv package..."
      - aws lambda publish-layer-version --layer-name my-python-dotenv-layer --description "Lambda layer with python-dotenv" --content S3Bucket=s3-doordash-landing,S3Key=python-dotenv.zip --compatible-runtimes python3.11
      - echo "Lambda layer creation complete!"

      # Extract the JSON file from the zip folder
      - echo "Extracting JSON file from the zip folder..."
      - unzip -o deployment_package.zip 2024-03-09-raw_input.json -d extracted_files/
      - echo "JSON file extracted successfully!"

      # Copy the extracted JSON file to the specified directory
      - echo "Copying 2024-03-09-raw_input.json to doordash-landing/raw_data/"
      - aws s3 cp extracted_files/2024-03-09-raw_input.json s3://s3-doordash-landing/doordash-landing/raw_data/
      - echo "File copied successfully!"
